s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print("my name is jigar".title())
print("tops".islower())
print("TOPS".isupper())
print(" ".isspace())
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("123".isnumeric())
print("tops".isalpha())
print(s.istitle())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("es"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T",2))
